### ISSUE TITLE
KeyError: 'isFoil'

### ISSUE THREAD

**Issue by Molakamur** [andli/pymkm#15]
Hello

First of all, thank you. I learned alot of your code :-).

I have a problem, that i sadly can not resolve by myself and i hope for a input from a kind soul.
pymkm tool gives me always a KeyError: 'isFoil'. I tried different Index (1.1; 1.41; 1.42) and always get the KeyError on Win10 and Win7. I also tried the "Hack" in the code, but it didnt help.

In the Attachments is my Python Shell.

![PythonShellKeyError](https://user-images.githubusercontent.com/58374312/69906230-a0c2f000-13c0-11ea-8f22-ef3f3960d30a.PNG)
 
I did not try everything in the tool, but everything else seems to work wonderfull.

**Comment by andli** [comment]
Hey, thanks for reporting this! Are you only trading Magic cards? Do you have any idea which card fails? This is probably an easy fix.

**Comment by andli** [comment]
@Molakamur if you know how, please clone the develop branch and see if the fix I pushed fixes your issue.

**Comment by Molakamur** [comment]
Hello Andli
Thanky you for the fast respond. No i have some Displays and Bundles too. The Number 1353 are exactly the diffrent kind of magic cards i have online.
I will try now the develop brach and report back.

**Comment by Molakamur** [comment]
Sadly i have a error. 

![PythonShell1 4 3](https://user-images.githubusercontent.com/58374312/69911167-d515cb00-1417-11ea-802e-0033ee314786.PNG)

**Comment by Molakamur** [comment]
I tried to update a single card with 1.4.3 and get the following error.
![SingelUpdateError01 12 2019](https://user-images.githubusercontent.com/58374312/69911829-85d49800-1421-11ea-8922-1a8c6771a50f.PNG)

With 1.4.2 it works with the same card.

**Comment by andli** [comment]
Ok, I fixed that one. I will try with a display and bundle on  my machine. Please pull this latest commit.

**Comment by Molakamur** [comment]
Hello andli
i tired out you latest commit. i got following error for stock update

![01 12 2019(3)](https://user-images.githubusercontent.com/58374312/69916170-e41c6d80-1457-11ea-84c7-17a0b3d7344a.PNG)

and following error for updating single foil card

![01 12 2019 foil singel card error](https://user-images.githubusercontent.com/58374312/69916172-ec74a880-1457-11ea-8ee7-1e014a534918.PNG)

thank you for your time

**Comment by andli** [comment]
Haha, thank you so much... redeemed the code. <3 I am making some progress here. Until now I have not officially supported other products than cards (Booster displays, Yu-gi-oh, bundles etc) but I am trying to make the app a bit more forgiving. I just pushed another update to the development branch, please try it out.

**Comment by andli** [comment]
Btw, I recommend running the app from a normal terminal like Powershell and then doing `python .\main.py` from the directory, it will make the progress bars a lot nicer.

**Comment by Molakamur** [comment]
Hello Andli

It worked! had no problem to update the stock.
i have to manually adjust some price's, but it will take away alot of work.

![Gutenschein Cardmarket 2](https://user-images.githubusercontent.com/58374312/69918977-3e2d2b00-1478-11ea-8a54-20d771f0d08c.PNG)

Thank you

**Comment by andli** [comment]
No problem, thank you for the "tip". :)
If you have any ideas on how to handle the prices that should not be updated like the others, please get back to me in a new ticket!

**Comment by andli** [comment]
PS @Molakamur I recommend that you remove the develop branch and go back to the master branch, I have released these improvements as a new release now. 🥇

**Comment by Molakamur** [comment]
Thank you. I will now test/use the tool and come back to you with some proposals/ideas.
Have a good week.
