### ISSUE TITLE
Web-based UI

### ISSUE THREAD

**Issue by aCard0s0** [andli/pymkm#16]
Greeting @andli ,

First of all, very nice tool, for quite some time I want to start something similar.
However, I always imagine something with web-bases UI client, using Django maybe.
Are you interested in start something similar that can work as top layer connected to cardmarket API where a user can better managing his store?

Best regards,
André Cardoso

**Comment by andli** [comment]
Hello @aCard0s0 ! Glad you like the tool. Yes I have thought about making a web front end for it, would be easy with Flask for example. I need a time transplant though... feel free to fork my repo, all you need would basically be the api part then, not my app cli frontend.
