### ISSUE TITLE
First time user experience

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#18]
Hey there!
I just stumbled upon and tried out your tool for the first time, awesome work! I will thoroughly try it out over the next days :)
I noticed some very minor errors that i was able to fix by myself but i thought I'd let you know:

First I tried importing a CSV file (my main use case is importing lists created with Delver Lens. I got the following error:
![pymkm](https://user-images.githubusercontent.com/20821078/81832732-22f23b80-953f-11ea-93db-c4eaef63be87.png)
I just included a static False in the get_price_for_product call, which fixed the issue.

For missing rarities I guess I can just add them in the config.json right? I would suggest adding all the missing rarities in the provided template for ease of use.
![image](https://user-images.githubusercontent.com/20821078/81834411-2edefd00-9541-11ea-964d-dee4ce922840.png)

Best wishes!

**Comment by andli** [comment]
Nice finds, I will fix this asap. :)

Thanks!
