### ISSUE TITLE
Problematic import niche cases 

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#19]
I found a few niche cases of cards not working when imported from CSV. Names that are less than 4 characters long:
Fog,Seventh Edition,1,,English

And cards that have a "," in their name:
Inner Calm, Outer Strength,Saviors of Kamigawa,1,,English

Not worth fixing probably, as these cases are pretty rare. Just for your info :)

**Comment by tarpan2** [comment]
These fail aswell, not sure why tbh:
Holy Strength,Eighth Edition,1,,English
Holy Strength,Ninth Edition,1,,English

**Comment by andli** [comment]
Yup, Cardmarket does not allow shorter strings than 4 characters in their API calls. Weird. The others I will look into. Thanks for reporting the issue(s)!

**Comment by andli** [comment]
I have updated README.md with the relevant info for csv importing. I have also added a fix for card names shorter than 4 characters.
Holy Strength fails because there is a card "Unholy Strength" in the same set that I have trouble matching for in a good way. Will push a fix soon. :)

**Comment by andli** [comment]
Release 1.6.1 out now with your fixes @tarpan2 - have great evening. 🍺

**Comment by tarpan2** [comment]
Thanks a lot for reacting so quickly! Another case that is not working are the flip cards from Innistrad:

Tormented Pariah,Innistrad,4,,English
Village Ironsmith,Innistrad,10,,English
Thraben Sentry,Innistrad,10,,English
Grizzled Outcasts,Innistrad,1,,English
Villagers of Estwald,Innistrad,4,,English

**Comment by tarpan2** [comment]
aaand one more:
Surging Aether,Coldsnap,7,,English

**Comment by andli** [comment]
Hey, I will fix these too of course. :) 
Again, thanks for reporting.
