### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#20]
Hey,

after some time using your amazing tool, I have a feature suggestion that would really help imo:

Generally, most calculated prices are close enough to what I would manually set. However that is not the case for cards in really bad condition. It would be awesome to be able to set discounts based on condition in the config.json, e.g. 10% lower price for GD, 20% for LP and so on.

Just a suggestion, thank you again for your work!

**Comment by andli** [comment]
Cool idea, I will look into it.

**Comment by andli** [comment]
```
"discount_by_condition": {
    "M": "1.5",
    "NM": "1",
    "EX": "0.9",
    "GD": "0.7",
    "LP": "0.6",
    "PL": "0.5",
    "PO": "0.4"
  },
```
Added a config feature like so, implemented and tested but not so extensively. By default all discounts are set to `1` but please do experiment with it. I will release a new version soon.

**Comment by tarpan2** [comment]
Looks very promising, thanks alot! I will also test the changes and let you know if I find any issues.
The condition mint is "MT" by the way :)
