### ISSUE TITLE
Updating part of the stock

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#21]
Hi! As I've been listing more and more cards, I recently exceeded 5000 different products so I'm running out of API-requests. Is there a way I can update only part of the stock with option 1? Like the first 4000 products one day and the rest on the next day?
This may not be relevant for most users so if I can add those limits to my local code that would help a lot already. Thanks for your great work once again!

**Comment by andli** [comment]
Sure, sounds like a good feature to have. I will look into it.

**Comment by andli** [comment]
The `develop` branch now has this feature if you want to try it out. I don't want to push the new version (1.7.0) until I have tested it a bit more myself since it is a pretty big change. :)

**Comment by tarpan2** [comment]
Cool, you are so fast to react, awesome :) I will try it out tonight!

I'd suggest introducing a constant in the config to set the condition for imports from csv instead of the hard coded "NM". Also maybe move filenames to the config file (list.csv, partial_stock_update.txt). Thats what I did locally at least because I keep the import list in a different place (I run a script there to merge multiple Delverlense-lists and apply the required format)

**Comment by tarpan2** [comment]
Okay some things I've noticed while testing the new feature:

1. It would be super useful to see a few numbers in the dialog while choosing the amount of articles to update. Like the number of cards in partial_stock_update.txt, the total number of products and the remaining API-calls for the day

2. Sometimes not all price updates shown in the best/worst diffs list are actually applied. Not sure how to reproduce this. I just updated 3000 products and printed the 30 best diffs. Out of those, 6 prices were not updated to the printed new value.
I'm pretty sure this happened in the old version too.

**Comment by andli** [comment]
(1.) yes I have been thinking about that too - there is no way for me of knowing the remaining API calls until I have done a call, but I could fire off a small one like account info to get that and add it to the menu.
(2.) really sounds like a bug. Given that description I could try to hunt it down.

**Comment by andli** [comment]
@tarpan2 the develop branch has been updated with a new preview. The fix for the second issue is not in that one yet though.

**Comment by tarpan2** [comment]
@andli awesome! (2.) above seems to happen only when a lot of prices have to get updated, maybe an issue with the chunking to 100 at a time?

Some minor UI things in the new dev version:
1. "Remaining API calls today:" shows the number of used calls, not the number of remaining calls
2. In the generation of the menu item you could remove the .\ so it makes more sense for different folders/linux/mac users >> "9: Import stock from .\./CSV/list.csv "

**Comment by tarpan2** [comment]
One more import string thats not working:
Castle,Seventh Edition,1,,English

**Comment by andli** [comment]
Ok, fixed it in 1.7.3, releasing that one today. Can you please submit the remaining bug ("Sometimes not all price updates shown in the best/worst diffs list are actually applied...") as a separate issue? Closing  this one for now. :)
