### ISSUE TITLE
Sometimes not all price updates are applied

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#22]
As you asked me to open a seperate issue, here it is :)

Sometimes not all price updates shown in the best/worst diffs list are actually applied. Not sure how to reproduce this. I just updated 3000 products and printed the 30 best diffs. Out of those, 6 prices were not updated to the printed new value.
I'm pretty sure this happened in the old version too.

seems to happen only when a lot of prices have to get updated, maybe an issue with the chunking to 100 at a time?

**Comment by andli** [comment]
Closing this, I don't think it is applicable in 2.0.0.
