### ISSUE TITLE
Price update crashes on special character

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#24]
# Context
When the stock contains this card: https://www.cardmarket.com/de/Magic/Products/Singles/2006-Player-Cards/Carlos-Romao
the whole script crashes and no prices get updated

## Steps to Reproduce
1. Add https://www.cardmarket.com/de/Magic/Products/Singles/2006-Player-Cards/Carlos-Romao to your stock (ArticleID: 874687504) 
2. Use option 1, update stock prices
3. App crashes
4. See error pymkm.pymkmapi.CardmarketError: {'error': 'Invalid POST data.'}

## Expected result
If the special char cannot be used for the stock update, a graceful handling without crashing the whole update would be great

## Actual result
crash, no prices updated but articles are written to partial_update anyway

## OS
Ubuntu 20.04

**Comment by andli** [comment]
Thank you for this, I will fix it asap.

**Comment by andli** [comment]
Special character works fine on my computer, cannot reproduce unfortunately.
Can you give me the entire error output please?

**Comment by andli** [comment]
Sorry @tarpan2 I did manage to reproduce and have fixed the issue now in 1.8.1.
