### ISSUE TITLE
Need beta testers for pymkm 2.0.0

### ISSUE THREAD

**Issue by andli** [andli/pymkm#25]
# Context
I need people who have large stocks to test the new much faster pymkm.

Please get in touch here if you are interested. Checkout the `async` branch and try it out!

**Comment by tarpan2** [comment]
I can try it on the weekend for sure! Currently I have around 16.000 cards listed :)

**Comment by tarpan2** [comment]
Anything specific that needs testing? Whats changed? :)

**Comment by tarpan2** [comment]
![image](https://user-images.githubusercontent.com/20821078/94992928-ac0d1c00-058d-11eb-80da-10fdca5c5113.png)

This is what I got so far, do I need to configure something first?

**Comment by andli** [comment]
Ah sorry, no that's not supposed to happen. The major change is just that instead of doing each price check sequentially, it now does them in  parallel, 100 at a time. So updating your stock should be at least 100x faster. That looks like a problem with Cardmarket though.

**Comment by andli** [comment]
Works for me, can you paste the relevant log entries from `pymkm.log`?

**Comment by andli** [comment]
Also, please try to update smaller chunks of your stock and see if that works, slowly working up until you see issues from the Cardmarket API. I don't know if they have any kind of request throttling on the web servers...

**Comment by tarpan2** [comment]
Doesn't work even when trying to update 1 item. Here are the log entries:
`2020-10-03 19:28:01,764 - pymkm.pymkm_app - DEBUG - >> Loading config file
2020-10-03 19:28:01,764 - pymkm.pymkmapi - DEBUG - >> Getting request quotas
2020-10-03 19:28:01,965 - pymkm.pymkmapi - DEBUG - >> Getting account details
2020-10-03 19:28:08,286 - pymkm.pymkmapi - DEBUG - -> get_stock start=None
2020-10-03 19:28:10,587 - pymkm.pymkm_app - ERROR - No response from API, exiting.
2020-10-03 19:28:13,909 - pymkm.pymkm_app - DEBUG - >> Loading config file
2020-10-03 19:28:13,910 - pymkm.pymkmapi - DEBUG - >> Getting request quotas
2020-10-03 19:28:14,022 - pymkm.pymkmapi - DEBUG - >> Getting account details
2020-10-03 19:28:17,894 - pymkm.pymkmapi - DEBUG - -> get_stock start=None
2020-10-03 19:28:19,436 - pymkm.pymkm_app - ERROR - No response from API, exiting.`

side note: my log file is 10,4 MB right now, maybe that should autoclean from time to time :D

**Comment by tarpan2** [comment]
Option 2 (updating single items) works for me:

Action number: 2
Search product name: 
inferno titan
Found: Inferno Titan[Magic 2012]..
Try to undercut local market? (slower, more requests) [y/N]: 
n
  Count  Name           Foil    Playset      Old price    New price    Diff
-------  -------------  ------  ---------  -----------  -----------  ------
      1  Inferno Titan                            0.89         0.99     0.1

Total price difference: 0.1.
Do you want to update these prices? [y/N]: 
y
Updating prices...
Price updated.

**Comment by andli** [comment]
Ok thanks, I will add a rotation to the logs so they don't grow infinitely 👍 
I will try to see why you get "no response from API" when it is apparently up...

**Comment by andli** [comment]
Added log rotation and better error message output from `get_stock`. Please try again. :)

**Comment by tarpan2** [comment]
Action number: 1
7086 articles found in previous updates, ignoring those. Remove partial_stock_update.txt if you want to clear the list.
Partial update? If so, enter number of cards (or press Enter to update all remaining stock): 
1
Try to undercut local market? (slower, more requests) [y/N]: 
n
No response from API.
2020-10-03 19:55:18,723 - pymkm.pymkm_app - ERROR - No response from API, exiting.
Traceback (most recent call last):
  File "pymkm.py", line 21, in <module>
    main()
  File "pymkm.py", line 16, in main
    app.start()
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 156, in start
    break_signal = menu.show()
  File "/home/tarpan/.local/lib/python3.8/site-packages/micromenu.py", line 48, in show
    func(**kwargs)
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 188, in update_stock_prices_to_trend
    uploadable_json, checked_articles = self.calculate_new_prices_for_stock(
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 918, in calculate_new_prices_for_stock
    filtered_stock_list = self.__filter(stock_list)
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 220, in __filter
    filtered_articles = [x for x in article_list if not filtered(x)]
TypeError: 'NoneType' object is not iterable

**Comment by andli** [comment]
Hmm, can you temporarily do `mv partial_stock_update.txt backup_partial_stock_update.txt` so we can eliminate that?
Also, I improved the filtering function that threw the error in my last push.

**Comment by tarpan2** [comment]
moved the partial update as you suggested and pulled again. Still the same issue:

Action number: 1
Partial update? If so, enter number of cards (or press Enter to update all remaining stock): 
1
Try to undercut local market? (slower, more requests) [y/N]: 
n
No response from API.
2020-10-03 20:11:35,981 - pymkm.pymkm_app - ERROR - No response from API, exiting.
Traceback (most recent call last):
  File "pymkm.py", line 21, in <module>
    main()
  File "pymkm.py", line 16, in main
    app.start()
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 156, in start
    break_signal = menu.show()
  File "/home/tarpan/.local/lib/python3.8/site-packages/micromenu.py", line 48, in show
    func(**kwargs)
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 188, in update_stock_prices_to_trend
    uploadable_json, checked_articles = self.calculate_new_prices_for_stock(
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 921, in calculate_new_prices_for_stock
    filtered_stock_list = self.__filter(stock_list)
  File "/home/tarpan/Downloads/MKM/pymkm/pymkm/pymkm_app.py", line 223, in __filter
    filtered_articles = [x for x in article_list if not filtered(x)]
TypeError: 'NoneType' object is not iterable

**Comment by andli** [comment]
I can't replicate the error which means I will have to generate a fake stock in my account with more cards so I can try to find the bug... :)

**Comment by andli** [comment]
Could you please check if your config.json contains all items in `config_template.json`? If not, copy over those you are missing. Especially `sticky_price_char`.

**Comment by tarpan2** [comment]
yes everything is the same except for some of the pricing values.
I also downloaded the branch in a brand new location, entered my credentials but it didn't work there either.

**Comment by andli** [comment]
Nice work, sorry it's not working. Could we maybe do a voice call over Discord or something to get this sorted? I would really like it if this async version works for users like you.

**Comment by tarpan2** [comment]
@andli sure we can do that, today after 7 pm or wednesday evening would work for me! I can also test the new version on windows/mac to see if this might be a linux issue

**Comment by andli** [comment]
Sorry @tarpan2 I have been quite swamped, did you manage to test on win/mac though?

**Comment by tarpan2** [comment]
Yes, same behavior on Windows for me

**Comment by andli** [comment]
Sorry for dropping this ball. I would really like to release 2.0.0 but I can't when one of my most frequent users can't use it. :) 
Can we schedule a session? I am on CET / Stockholm time zone.

**Comment by tarpan2** [comment]
Hi I'm in the same time zone (Germany). How about tonight, any time after 7 PM would work for me.
Do you know if anyone else tested this version yet?

**Comment by andli** [comment]
No other testers no. But your case is probably worst case, so that's fine. :)
Here is a link to a discord server we can use: https://discord.gg/ReuAM3q

**Comment by tarpan2** [comment]
@andli I'm online in case you have time right now ;-)

**Comment by tarpan2** [comment]
sorry I revoked the keys probably before your test finished. No 307 issues any more but its starting at 1 again for each itearation of the 100 threads

**Comment by andli** [comment]
pull the last commit where I polished it some more. now: bedtime. :)
feel free to put messages in the Discord if you want easier messaging.
