### ISSUE TITLE
Failed CS

### ISSUE THREAD

**Issue by tarpan2** [andli/pymkm#26]
# Context
Tried to import the following list.csv (Master branch):

Card,Set Name,Quantity,Foil,Language
Tormented Soul,Magic 2012,1,,German

## Steps to Reproduce
1. update your list file to the above mentioned
2. Use option 9, import stock
3. Success!
4. Card does not appear in stock

## Expected result
Card is listed as usual

## Actual result
Nothing happened

## OS
Ubuntu 20.04

**Comment by andli** [comment]
Yes, I found this one and it is fixed in 2.0.0.
