### ISSUE TITLE
Problem with inserting stock

### ISSUE THREAD

**Issue by Barracosa** [andli/pymkm#27]
When I try to use your script I cannot insert any stock.
I looked at the reponse and cardmarket returns, for example:

r.content
b'{"inserted":[{"success":false,"tried":{"idProduct":"2767","idLanguage":"1","count":"1","comments":"a","price":"0.13","condition":"nm","isFoil":"false","amount":"1"},"error":"An error has ocurred, the card has NOT been listed."}]}'

So it says success is dalse, and the error is just "An error has ocurred, the card has NOT been listed".
Does the code work on your side?

**Comment by andli** [comment]
Can you post the log from `log_pymkm.log`? Which version are you using?

**Comment by Barracosa** [comment]
I cleaned the folder already.
The issue is that you change everything to minuscule because of the "true/false" problem.
However, for the card state (NM,EX, etc..) it has to be in majuscule, otherwise the API throws an error.

**Comment by andli** [comment]
Sorry, I can't seem to find a place where the app tries to add stock with a lowercase card condition. Could you please run it again and give me the log output?

**Comment by andli** [comment]
Fixed in 1.8.2.
