### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by rasmaral** [andli/pymkm#30]
# Context
Sorry Andreas but im a noob :) I hope you can help me. I installed python i tried to run the pip install command but its not working.
Do i need to put your pymkm-master files inside the python instal path? IDK sorry for this and thanks in advance :)

**Comment by andli** [comment]
No problem. Install python, good. Then you open a terminal (command prompt, powershell, etc) and navigate to the directory you downloaded pymkm to. Then type `python pymkm.py` and you should be good to go. 
If you need more help, hop in to the Discord server and we will get you set up: https://discord.gg/E7DxCe9XVv
