### ISSUE TITLE
Import from list.csv

### ISSUE THREAD

**Issue by moteuchi** [andli/pymkm#31]
# Context
The language of imported cards are changed to "French".

## Steps to Reproduce
1. Create my list.csv
2. Content of my list.csv:

Card,Set Name,Quantity,Foil,Language
Heliod's Pilgrim,Theros Beyond Death,1,,English
Dreadful Apathy,Theros Beyond Death,1,,English
Indomitable Will,Theros Beyond Death,1,,English
Triumphant Surge,Theros Beyond Death,1,,English
Pious Wayfarer,Theros Beyond Death,1,,English

3. Select "8: Import stock from list.csv"

## Expected result
Cards imported to Cardmarket should be in English Language.

## Actual result
Cards imported to Cardmarket are in French Language

## OS
Ubuntu 18.04 // Python 3.8.7
PyMkm 2.3.0

**Comment by andli** [comment]
Interesting, I will have a look asap. Thanks for reporting!

**Comment by moteuchi** [comment]
Hi Andli,
I just did another test.
Imported Japanese card are changed to Portuguese.

**Comment by andli** [comment]
This makes it very obvious what is wrong. Will fix. :)

**Comment by andli** [comment]
@moteuchi please verify that it works for you too :)

**Comment by moteuchi** [comment]
It works perfectly! Thanks Andli!

**Comment by andli** [comment]
> It works perfectly! Thanks Andli!

If you need speedier assistance, hop in on the Discord server I have linked in the README.
