### ISSUE TITLE
Is there a way to just get the price of a card given its name?

### ISSUE THREAD

**Issue by gerardnavarro22** [andli/pymkm#33]
Just need a python program to do this and I've seen this is the only python project that uses the cardmarket api.

**Comment by andli** [comment]
That seems like a useful feature, for example as a pure CLI command and not in the "GUI". You would need to know a name that gives an exact match or the product ID at Cardmarket.

**Comment by andli** [comment]
@gerardnavarro22 please get back to me here or in the Discord server with a more detailed description of how you would like to use this feature. :)

**Comment by andli** [comment]
ping @gerardnavarro22 , I will close this for now but please get back to me if you still want this done.
