### ISSUE TITLE
Error - <Response [403]

### ISSUE THREAD

**Issue by khalidi1987** [andli/pymkm#34]
Hi,

thanks for the tool. 
I getting this error:
` pymkm.pymkmapi - ERROR - <Response [403]> for https://api.cardmarket.com/ws/v2.0/output.json/account`

Could you please help?

**Comment by andli** [comment]
No unfortunately this is because Cardmarket has taken down their API service due to their internal issues. It is out of my hands. :(

**Comment by andli** [comment]
Read more here: https://www.cardmarket.com/en/Magic/News/Statement-On-Cardmarket-Outage

**Comment by khalidi1987** [comment]
Thanks for the information. I will check the link.
